// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CompanymediashareDocumentDataSlicesSlice = SocialMediaSlice;

/**
 * Content for companyMediaShare documents
 */
interface CompanymediashareDocumentData {
  /**
   * Slice Zone field in *companyMediaShare*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: companymediashare.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CompanymediashareDocumentDataSlicesSlice>;
}

/**
 * companyMediaShare document from Prismic
 *
 * - **API ID**: `companymediashare`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CompanymediashareDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CompanymediashareDocumentData>,
    "companymediashare",
    Lang
  >;

type NavigationmenuDocumentDataSlicesSlice = NavigationItensSlice;

/**
 * Content for navigationMenu documents
 */
interface NavigationmenuDocumentData {
  /**
   * Slice Zone field in *navigationMenu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationmenuDocumentDataSlicesSlice>;

  /**
   * CVMLogo field in *navigationMenu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.cvmlogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cvmlogo: prismic.ImageField<never>;

  /**
   * HomeLink field in *navigationMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.homelink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  homelink: prismic.LinkField;
}

/**
 * navigationMenu document from Prismic
 *
 * - **API ID**: `navigationmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationmenuDocumentData>,
    "navigationmenu",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ProjectAndSubprojectsSlice
  | NewsCardListSlice
  | NewsSlice
  | HelpSlice
  | PhotosSlice
  | GallerySlice
  | ProjectsSlice
  | OurHistorySlice
  | InstitutionalVideoSlice
  | StackholdersSlice
  | SocialImpactSlice
  | DonateSlice
  | HeroSlice
  | MissionVisionValuesSlice
  | ContactAndSocialMediaSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | CompanymediashareDocument
  | NavigationmenuDocument
  | PageDocument;

/**
 * Primary content in *ContactAndSocialMedia → Primary*
 */
export interface ContactAndSocialMediaSliceDefaultPrimary {
  /**
   * sectionTitle field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * Address field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Phone field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Primary content in *ContactAndSocialMedia → Items*
 */
export interface ContactAndSocialMediaSliceDefaultItem {
  /**
   * SocialMediaIcon field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmediaicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialmediaicon: prismic.ImageField<never>;

  /**
   * SocialMediaLink field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmedialink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialmedialink: prismic.LinkField;

  /**
   * SocialMediaLabel field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmedialabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialmedialabel: prismic.KeyTextField;
}

/**
 * Default variation for ContactAndSocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndSocialMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactAndSocialMediaSliceDefaultPrimary>,
  Simplify<ContactAndSocialMediaSliceDefaultItem>
>;

/**
 * Slice variation for *ContactAndSocialMedia*
 */
type ContactAndSocialMediaSliceVariation = ContactAndSocialMediaSliceDefault;

/**
 * ContactAndSocialMedia Shared Slice
 *
 * - **API ID**: `contact_and_social_media`
 * - **Description**: ContactAndSocialMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndSocialMediaSlice = prismic.SharedSlice<
  "contact_and_social_media",
  ContactAndSocialMediaSliceVariation
>;

/**
 * Primary content in *Donate → Primary*
 */
export interface DonateSliceDefaultPrimary {
  /**
   * donateImage field in *Donate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donate.primary.donateimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donateimage: prismic.ImageField<never>;
}

/**
 * Default variation for Donate Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DonateSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DonateSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Donate*
 */
type DonateSliceVariation = DonateSliceDefault;

/**
 * Donate Shared Slice
 *
 * - **API ID**: `donate`
 * - **Description**: Donate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DonateSlice = prismic.SharedSlice<"donate", DonateSliceVariation>;

/**
 * Primary content in *Gallery → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * sectionTitle field in *Gallery → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * albumImage field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].albumimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  albumimage: prismic.ImageField<never>;

  /**
   * albumTitle field in *Gallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].albumtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  albumtitle: prismic.KeyTextField;

  /**
   * albumLink field in *Gallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].albumlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  albumlink: prismic.LinkField;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Help → Primary*
 */
export interface HelpSliceDefaultPrimary {
  /**
   * sectionTitle field in *Help → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: help.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;
}

/**
 * Primary content in *Help → Items*
 */
export interface HelpSliceDefaultItem {
  /**
   * helpImage field in *Help → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: help.items[].helpimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  helpimage: prismic.ImageField<never>;

  /**
   * helpTitle field in *Help → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: help.items[].helptitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  helptitle: prismic.KeyTextField;

  /**
   * helpDescription field in *Help → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: help.items[].helpdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  helpdescription: prismic.KeyTextField;

  /**
   * helpBody field in *Help → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: help.items[].helpbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  helpbody: prismic.RichTextField;

  /**
   * helpBodyAdditionalImage field in *Help → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: help.items[].helpbodyadditionalimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  helpbodyadditionalimage: prismic.ImageField<never>;
}

/**
 * Default variation for Help Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HelpSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HelpSliceDefaultPrimary>,
  Simplify<HelpSliceDefaultItem>
>;

/**
 * Slice variation for *Help*
 */
type HelpSliceVariation = HelpSliceDefault;

/**
 * Help Shared Slice
 *
 * - **API ID**: `help`
 * - **Description**: Help
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HelpSlice = prismic.SharedSlice<"help", HelpSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * herospancolor field in *Hero → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herospancolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  herospancolor: prismic.ColorField;

  /**
   * heroTitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitle: prismic.KeyTextField;

  /**
   * heroTitleSpan field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitlespan
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitlespan: prismic.KeyTextField;

  /**
   * heroTitleComplementaryText field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitlecomplementarytext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitlecomplementarytext: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * HeroCarrouselImage field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].herocarrouselimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herocarrouselimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *InstitutionalVideo → Primary*
 */
export interface InstitutionalVideoSliceDefaultPrimary {
  /**
   * sectionTitle field in *InstitutionalVideo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: institutional_video.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * videoUrl field in *InstitutionalVideo → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: institutional_video.primary.videourl
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  videourl: prismic.EmbedField;
}

/**
 * Default variation for InstitutionalVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstitutionalVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstitutionalVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InstitutionalVideo*
 */
type InstitutionalVideoSliceVariation = InstitutionalVideoSliceDefault;

/**
 * InstitutionalVideo Shared Slice
 *
 * - **API ID**: `institutional_video`
 * - **Description**: InstitutionalVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstitutionalVideoSlice = prismic.SharedSlice<
  "institutional_video",
  InstitutionalVideoSliceVariation
>;

/**
 * Primary content in *MissionVisionValues → Items*
 */
export interface MissionVisionValuesSliceDefaultItem {
  /**
   * CardImage field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * CardTitle field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardtitle: prismic.KeyTextField;

  /**
   * CardBody field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardbody: prismic.RichTextField;
}

/**
 * Default variation for MissionVisionValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionVisionValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MissionVisionValuesSliceDefaultItem>
>;

/**
 * Slice variation for *MissionVisionValues*
 */
type MissionVisionValuesSliceVariation = MissionVisionValuesSliceDefault;

/**
 * MissionVisionValues Shared Slice
 *
 * - **API ID**: `mission_vision_values`
 * - **Description**: MissionVisionValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionVisionValuesSlice = prismic.SharedSlice<
  "mission_vision_values",
  MissionVisionValuesSliceVariation
>;

/**
 * Primary content in *NavigationItens → Primary*
 */
export interface NavigationItensSliceDefaultPrimary {
  /**
   * dropdownMenuLabel field in *NavigationItens → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.primary.dropdownmenulabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  dropdownmenulabel: prismic.KeyTextField;

  /**
   * drodpownMenuItem field in *NavigationItens → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.primary.drodpownmenuitem
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  drodpownmenuitem: prismic.KeyTextField;

  /**
   * dropdownMenuItemLink field in *NavigationItens → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.primary.dropdownmenuitemlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  dropdownmenuitemlink: prismic.LinkField;
}

/**
 * Primary content in *NavigationItens → Items*
 */
export interface NavigationItensSliceDefaultItem {
  /**
   * Label field in *NavigationItens → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *NavigationItens → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavigationItens Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItensSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItensSliceDefaultPrimary>,
  Simplify<NavigationItensSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItens*
 */
type NavigationItensSliceVariation = NavigationItensSliceDefault;

/**
 * NavigationItens Shared Slice
 *
 * - **API ID**: `navigation_itens`
 * - **Description**: NavigationItens
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItensSlice = prismic.SharedSlice<
  "navigation_itens",
  NavigationItensSliceVariation
>;

/**
 * Primary content in *News → Primary*
 */
export interface NewsSliceDefaultPrimary {
  /**
   * newsTitle field in *News → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.primary.newstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newstitle: prismic.KeyTextField;

  /**
   * newsBody field in *News → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.primary.newsbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  newsbody: prismic.RichTextField;

  /**
   * newsCoverImage field in *News → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.primary.newscoverimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  newscoverimage: prismic.ImageField<never>;
}

/**
 * Default variation for News Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *News*
 */
type NewsSliceVariation = NewsSliceDefault;

/**
 * News Shared Slice
 *
 * - **API ID**: `news`
 * - **Description**: News
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSlice = prismic.SharedSlice<"news", NewsSliceVariation>;

/**
 * Primary content in *NewsCardList → Primary*
 */
export interface NewsCardListSliceDefaultPrimary {
  /**
   * sectionTitle field in *NewsCardList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * social media label field in *NewsCardList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.primary.social_media_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_label: prismic.KeyTextField;

  /**
   * social media image field in *NewsCardList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.primary.social_media_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_image: prismic.ImageField<never>;

  /**
   * social_media_link field in *NewsCardList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.primary.social_media_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_link: prismic.KeyTextField;
}

/**
 * Primary content in *NewsCardList → Items*
 */
export interface NewsCardListSliceDefaultItem {
  /**
   * newsTitle field in *NewsCardList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.items[].newstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newstitle: prismic.KeyTextField;

  /**
   * newsResume field in *NewsCardList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.items[].newsresume
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsresume: prismic.KeyTextField;

  /**
   * newsCoverImage field in *NewsCardList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.items[].newscoverimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  newscoverimage: prismic.ImageField<never>;

  /**
   * newsLink field in *NewsCardList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: news_card_list.items[].newslink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  newslink: prismic.LinkField;
}

/**
 * Default variation for NewsCardList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsCardListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsCardListSliceDefaultPrimary>,
  Simplify<NewsCardListSliceDefaultItem>
>;

/**
 * Slice variation for *NewsCardList*
 */
type NewsCardListSliceVariation = NewsCardListSliceDefault;

/**
 * NewsCardList Shared Slice
 *
 * - **API ID**: `news_card_list`
 * - **Description**: NewsCardList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsCardListSlice = prismic.SharedSlice<
  "news_card_list",
  NewsCardListSliceVariation
>;

/**
 * Primary content in *OurHistory → Primary*
 */
export interface OurHistorySliceDefaultPrimary {
  /**
   * sectiontitle field in *OurHistory → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_history.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sectiontitle: prismic.RichTextField;
}

/**
 * Primary content in *OurHistory → Items*
 */
export interface OurHistorySliceDefaultItem {
  /**
   * timelineImage field in *OurHistory → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_history.items[].timelineimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  timelineimage: prismic.ImageField<never>;

  /**
   * timelineTitle field in *OurHistory → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_history.items[].timelinetitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  timelinetitle: prismic.KeyTextField;

  /**
   * timelineBody field in *OurHistory → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_history.items[].timelinebody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  timelinebody: prismic.RichTextField;

  /**
   * timelineTitleColor field in *OurHistory → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: our_history.items[].timelinetitlecolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  timelinetitlecolor: prismic.ColorField;
}

/**
 * Default variation for OurHistory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurHistorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurHistorySliceDefaultPrimary>,
  Simplify<OurHistorySliceDefaultItem>
>;

/**
 * Slice variation for *OurHistory*
 */
type OurHistorySliceVariation = OurHistorySliceDefault;

/**
 * OurHistory Shared Slice
 *
 * - **API ID**: `our_history`
 * - **Description**: OurHistory
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurHistorySlice = prismic.SharedSlice<
  "our_history",
  OurHistorySliceVariation
>;

/**
 * Primary content in *Photos → Primary*
 */
export interface PhotosSliceDefaultPrimary {
  /**
   * sectionTitle field in *Photos → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: photos.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;
}

/**
 * Primary content in *Photos → Items*
 */
export interface PhotosSliceDefaultItem {
  /**
   * picture field in *Photos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: photos.items[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Default variation for Photos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PhotosSliceDefaultPrimary>,
  Simplify<PhotosSliceDefaultItem>
>;

/**
 * Slice variation for *Photos*
 */
type PhotosSliceVariation = PhotosSliceDefault;

/**
 * Photos Shared Slice
 *
 * - **API ID**: `photos`
 * - **Description**: Photos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PhotosSlice = prismic.SharedSlice<"photos", PhotosSliceVariation>;

/**
 * Primary content in *ProjectAndSubprojects → Primary*
 */
export interface ProjectAndSubprojectsSliceDefaultPrimary {
  /**
   * title field in *ProjectAndSubprojects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * projectBody field in *ProjectAndSubprojects → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.primary.projectbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectbody: prismic.RichTextField;

  /**
   * projectImage field in *ProjectAndSubprojects → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.primary.projectimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectimage: prismic.ImageField<never>;
}

/**
 * Primary content in *ProjectAndSubprojects → Items*
 */
export interface ProjectAndSubprojectsSliceDefaultItem {
  /**
   * projectTitle field in *ProjectAndSubprojects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.items[].projecttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  projecttitle: prismic.KeyTextField;

  /**
   * projectImage field in *ProjectAndSubprojects → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.items[].projectimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectimage: prismic.ImageField<never>;

  /**
   * projectLink field in *ProjectAndSubprojects → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project_and_subprojects.items[].projectlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  projectlink: prismic.LinkField;
}

/**
 * Default variation for ProjectAndSubprojects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectAndSubprojectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectAndSubprojectsSliceDefaultPrimary>,
  Simplify<ProjectAndSubprojectsSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectAndSubprojects*
 */
type ProjectAndSubprojectsSliceVariation = ProjectAndSubprojectsSliceDefault;

/**
 * ProjectAndSubprojects Shared Slice
 *
 * - **API ID**: `project_and_subprojects`
 * - **Description**: ProjectAndSubprojects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectAndSubprojectsSlice = prismic.SharedSlice<
  "project_and_subprojects",
  ProjectAndSubprojectsSliceVariation
>;

/**
 * Primary content in *Projects → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * sectionTitle field in *Projects → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;
}

/**
 * Primary content in *Projects → Items*
 */
export interface ProjectsSliceDefaultItem {
  /**
   * projectTitle field in *Projects → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].projecttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  projecttitle: prismic.KeyTextField;

  /**
   * projectBody field in *Projects → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].projectbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projectbody: prismic.RichTextField;

  /**
   * projectImagem field in *Projects → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.items[].projectimagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  projectimagem: prismic.ImageField<never>;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  Simplify<ProjectsSliceDefaultItem>
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SocialImpact → Primary*
 */
export interface SocialImpactSliceDefaultPrimary {
  /**
   * SocialImpactTitle field in *SocialImpact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_impact.primary.socialimpacttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialimpacttitle: prismic.KeyTextField;

  /**
   * socialImpactImage field in *SocialImpact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_impact.primary.socialimpactimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialimpactimage: prismic.ImageField<never>;
}

/**
 * Default variation for SocialImpact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialImpactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialImpactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialImpact*
 */
type SocialImpactSliceVariation = SocialImpactSliceDefault;

/**
 * SocialImpact Shared Slice
 *
 * - **API ID**: `social_impact`
 * - **Description**: SocialImpact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialImpactSlice = prismic.SharedSlice<
  "social_impact",
  SocialImpactSliceVariation
>;

/**
 * Primary content in *SocialMedia → Items*
 */
export interface SocialMediaSliceDefaultItem {
  /**
   * socialLink field in *SocialMedia → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.items[].sociallink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sociallink: prismic.LinkField;

  /**
   * socialLogo field in *SocialMedia → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.items[].sociallogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  sociallogo: prismic.ImageField<never>;

  /**
   * socialName field in *SocialMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.items[].socialname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialname: prismic.KeyTextField;
}

/**
 * Default variation for SocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialMediaSliceDefaultItem>
>;

/**
 * Slice variation for *SocialMedia*
 */
type SocialMediaSliceVariation = SocialMediaSliceDefault;

/**
 * SocialMedia Shared Slice
 *
 * - **API ID**: `social_media`
 * - **Description**: SocialMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSlice = prismic.SharedSlice<
  "social_media",
  SocialMediaSliceVariation
>;

/**
 * Primary content in *Stackholders → Primary*
 */
export interface StackholdersSliceDefaultPrimary {
  /**
   * stackholdersTitle field in *Stackholders → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.primary.stackholderstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stackholderstitle: prismic.KeyTextField;
}

/**
 * Primary content in *Stackholders → Items*
 */
export interface StackholdersSliceDefaultItem {
  /**
   * stackholderImage field in *Stackholders → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholderimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  stackholderimage: prismic.ImageField<never>;

  /**
   * stackholderName field in *Stackholders → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholdername
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stackholdername: prismic.KeyTextField;

  /**
   * stackholderLink field in *Stackholders → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholderlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stackholderlink: prismic.LinkField;
}

/**
 * Default variation for Stackholders Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackholdersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StackholdersSliceDefaultPrimary>,
  Simplify<StackholdersSliceDefaultItem>
>;

/**
 * Slice variation for *Stackholders*
 */
type StackholdersSliceVariation = StackholdersSliceDefault;

/**
 * Stackholders Shared Slice
 *
 * - **API ID**: `stackholders`
 * - **Description**: Stackholders
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackholdersSlice = prismic.SharedSlice<
  "stackholders",
  StackholdersSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CompanymediashareDocument,
      CompanymediashareDocumentData,
      CompanymediashareDocumentDataSlicesSlice,
      NavigationmenuDocument,
      NavigationmenuDocumentData,
      NavigationmenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactAndSocialMediaSlice,
      ContactAndSocialMediaSliceDefaultPrimary,
      ContactAndSocialMediaSliceDefaultItem,
      ContactAndSocialMediaSliceVariation,
      ContactAndSocialMediaSliceDefault,
      DonateSlice,
      DonateSliceDefaultPrimary,
      DonateSliceVariation,
      DonateSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      HelpSlice,
      HelpSliceDefaultPrimary,
      HelpSliceDefaultItem,
      HelpSliceVariation,
      HelpSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      InstitutionalVideoSlice,
      InstitutionalVideoSliceDefaultPrimary,
      InstitutionalVideoSliceVariation,
      InstitutionalVideoSliceDefault,
      MissionVisionValuesSlice,
      MissionVisionValuesSliceDefaultItem,
      MissionVisionValuesSliceVariation,
      MissionVisionValuesSliceDefault,
      NavigationItensSlice,
      NavigationItensSliceDefaultPrimary,
      NavigationItensSliceDefaultItem,
      NavigationItensSliceVariation,
      NavigationItensSliceDefault,
      NewsSlice,
      NewsSliceDefaultPrimary,
      NewsSliceVariation,
      NewsSliceDefault,
      NewsCardListSlice,
      NewsCardListSliceDefaultPrimary,
      NewsCardListSliceDefaultItem,
      NewsCardListSliceVariation,
      NewsCardListSliceDefault,
      OurHistorySlice,
      OurHistorySliceDefaultPrimary,
      OurHistorySliceDefaultItem,
      OurHistorySliceVariation,
      OurHistorySliceDefault,
      PhotosSlice,
      PhotosSliceDefaultPrimary,
      PhotosSliceDefaultItem,
      PhotosSliceVariation,
      PhotosSliceDefault,
      ProjectAndSubprojectsSlice,
      ProjectAndSubprojectsSliceDefaultPrimary,
      ProjectAndSubprojectsSliceDefaultItem,
      ProjectAndSubprojectsSliceVariation,
      ProjectAndSubprojectsSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceDefaultItem,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SocialImpactSlice,
      SocialImpactSliceDefaultPrimary,
      SocialImpactSliceVariation,
      SocialImpactSliceDefault,
      SocialMediaSlice,
      SocialMediaSliceDefaultItem,
      SocialMediaSliceVariation,
      SocialMediaSliceDefault,
      StackholdersSlice,
      StackholdersSliceDefaultPrimary,
      StackholdersSliceDefaultItem,
      StackholdersSliceVariation,
      StackholdersSliceDefault,
    };
  }
}
