// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type NavigationmenuDocumentDataSlicesSlice = NavigationItensSlice;

/**
 * Content for navigationMenu documents
 */
interface NavigationmenuDocumentData {
  /**
   * Slice Zone field in *navigationMenu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationmenuDocumentDataSlicesSlice>;

  /**
   * CVMLogo field in *navigationMenu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.cvmlogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cvmlogo: prismic.ImageField<never>;

  /**
   * HomeLink field in *navigationMenu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigationmenu.homelink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  homelink: prismic.LinkField;
}

/**
 * navigationMenu document from Prismic
 *
 * - **API ID**: `navigationmenu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationmenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationmenuDocumentData>,
    "navigationmenu",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StackholdersSlice
  | SocialImpactSlice
  | DonateSlice
  | HeroSlice
  | MissionVisionValuesSlice
  | ContactAndSocialMediaSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = NavigationmenuDocument | PageDocument;

/**
 * Primary content in *ContactAndSocialMedia → Primary*
 */
export interface ContactAndSocialMediaSliceDefaultPrimary {
  /**
   * sectionTitle field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.sectiontitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectiontitle: prismic.KeyTextField;

  /**
   * Address field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * Phone field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *ContactAndSocialMedia → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Primary content in *ContactAndSocialMedia → Items*
 */
export interface ContactAndSocialMediaSliceDefaultItem {
  /**
   * SocialMediaIcon field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmediaicon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialmediaicon: prismic.ImageField<never>;

  /**
   * SocialMediaLink field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmedialink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialmedialink: prismic.LinkField;

  /**
   * SocialMediaLabel field in *ContactAndSocialMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_and_social_media.items[].socialmedialabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialmedialabel: prismic.KeyTextField;
}

/**
 * Default variation for ContactAndSocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndSocialMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactAndSocialMediaSliceDefaultPrimary>,
  Simplify<ContactAndSocialMediaSliceDefaultItem>
>;

/**
 * Slice variation for *ContactAndSocialMedia*
 */
type ContactAndSocialMediaSliceVariation = ContactAndSocialMediaSliceDefault;

/**
 * ContactAndSocialMedia Shared Slice
 *
 * - **API ID**: `contact_and_social_media`
 * - **Description**: ContactAndSocialMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactAndSocialMediaSlice = prismic.SharedSlice<
  "contact_and_social_media",
  ContactAndSocialMediaSliceVariation
>;

/**
 * Primary content in *Donate → Primary*
 */
export interface DonateSliceDefaultPrimary {
  /**
   * donateImage field in *Donate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: donate.primary.donateimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  donateimage: prismic.ImageField<never>;
}

/**
 * Default variation for Donate Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DonateSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DonateSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Donate*
 */
type DonateSliceVariation = DonateSliceDefault;

/**
 * Donate Shared Slice
 *
 * - **API ID**: `donate`
 * - **Description**: Donate
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DonateSlice = prismic.SharedSlice<"donate", DonateSliceVariation>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * herospancolor field in *Hero → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herospancolor
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  herospancolor: prismic.ColorField;

  /**
   * heroTitle field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitle: prismic.KeyTextField;

  /**
   * heroTitleSpan field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitlespan
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitlespan: prismic.KeyTextField;

  /**
   * heroTitleComplementaryText field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitlecomplementarytext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitlecomplementarytext: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * HeroCarrouselImage field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].herocarrouselimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  herocarrouselimage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *MissionVisionValues → Items*
 */
export interface MissionVisionValuesSliceDefaultItem {
  /**
   * CardImage field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * CardTitle field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardtitle: prismic.KeyTextField;

  /**
   * CardBody field in *MissionVisionValues → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mission_vision_values.items[].cardbody
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardbody: prismic.RichTextField;
}

/**
 * Default variation for MissionVisionValues Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionVisionValuesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MissionVisionValuesSliceDefaultItem>
>;

/**
 * Slice variation for *MissionVisionValues*
 */
type MissionVisionValuesSliceVariation = MissionVisionValuesSliceDefault;

/**
 * MissionVisionValues Shared Slice
 *
 * - **API ID**: `mission_vision_values`
 * - **Description**: MissionVisionValues
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MissionVisionValuesSlice = prismic.SharedSlice<
  "mission_vision_values",
  MissionVisionValuesSliceVariation
>;

/**
 * Primary content in *NavigationItens → Primary*
 */
export interface NavigationItensSliceDefaultPrimary {
  /**
   * transparency field in *NavigationItens → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.primary.transparency
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  transparency: prismic.SelectField<"1" | "2">;
}

/**
 * Primary content in *NavigationItens → Items*
 */
export interface NavigationItensSliceDefaultItem {
  /**
   * Label field in *NavigationItens → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * link field in *NavigationItens → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_itens.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for NavigationItens Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItensSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItensSliceDefaultPrimary>,
  Simplify<NavigationItensSliceDefaultItem>
>;

/**
 * Slice variation for *NavigationItens*
 */
type NavigationItensSliceVariation = NavigationItensSliceDefault;

/**
 * NavigationItens Shared Slice
 *
 * - **API ID**: `navigation_itens`
 * - **Description**: NavigationItens
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItensSlice = prismic.SharedSlice<
  "navigation_itens",
  NavigationItensSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SocialImpact → Primary*
 */
export interface SocialImpactSliceDefaultPrimary {
  /**
   * SocialImpactTitle field in *SocialImpact → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_impact.primary.socialimpacttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  socialimpacttitle: prismic.KeyTextField;

  /**
   * socialImpactImage field in *SocialImpact → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_impact.primary.socialimpactimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialimpactimage: prismic.ImageField<never>;
}

/**
 * Default variation for SocialImpact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialImpactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialImpactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialImpact*
 */
type SocialImpactSliceVariation = SocialImpactSliceDefault;

/**
 * SocialImpact Shared Slice
 *
 * - **API ID**: `social_impact`
 * - **Description**: SocialImpact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialImpactSlice = prismic.SharedSlice<
  "social_impact",
  SocialImpactSliceVariation
>;

/**
 * Primary content in *Stackholders → Primary*
 */
export interface StackholdersSliceDefaultPrimary {
  /**
   * stackholdersTitle field in *Stackholders → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.primary.stackholderstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stackholderstitle: prismic.KeyTextField;
}

/**
 * Primary content in *Stackholders → Items*
 */
export interface StackholdersSliceDefaultItem {
  /**
   * stackholderImage field in *Stackholders → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholderimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  stackholderimage: prismic.ImageField<never>;

  /**
   * stackholderName field in *Stackholders → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholdername
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  stackholdername: prismic.KeyTextField;

  /**
   * stackholderLink field in *Stackholders → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stackholders.items[].stackholderlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stackholderlink: prismic.LinkField;
}

/**
 * Default variation for Stackholders Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackholdersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StackholdersSliceDefaultPrimary>,
  Simplify<StackholdersSliceDefaultItem>
>;

/**
 * Slice variation for *Stackholders*
 */
type StackholdersSliceVariation = StackholdersSliceDefault;

/**
 * Stackholders Shared Slice
 *
 * - **API ID**: `stackholders`
 * - **Description**: Stackholders
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StackholdersSlice = prismic.SharedSlice<
  "stackholders",
  StackholdersSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationmenuDocument,
      NavigationmenuDocumentData,
      NavigationmenuDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactAndSocialMediaSlice,
      ContactAndSocialMediaSliceDefaultPrimary,
      ContactAndSocialMediaSliceDefaultItem,
      ContactAndSocialMediaSliceVariation,
      ContactAndSocialMediaSliceDefault,
      DonateSlice,
      DonateSliceDefaultPrimary,
      DonateSliceVariation,
      DonateSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      MissionVisionValuesSlice,
      MissionVisionValuesSliceDefaultItem,
      MissionVisionValuesSliceVariation,
      MissionVisionValuesSliceDefault,
      NavigationItensSlice,
      NavigationItensSliceDefaultPrimary,
      NavigationItensSliceDefaultItem,
      NavigationItensSliceVariation,
      NavigationItensSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SocialImpactSlice,
      SocialImpactSliceDefaultPrimary,
      SocialImpactSliceVariation,
      SocialImpactSliceDefault,
      StackholdersSlice,
      StackholdersSliceDefaultPrimary,
      StackholdersSliceDefaultItem,
      StackholdersSliceVariation,
      StackholdersSliceDefault,
    };
  }
}
