// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_and_social_media: dynamic(() => import("./ContactAndSocialMedia")),
  donate: dynamic(() => import("./Donate")),
  gallery: dynamic(() => import("./Gallery")),
  help: dynamic(() => import("./Help")),
  hero: dynamic(() => import("./Hero")),
  institutional_video: dynamic(() => import("./InstitutionalVideo")),
  mission_vision_values: dynamic(() => import("./MissionVisionValues")),
  navigation_itens: dynamic(() => import("./NavigationItens")),
  news: dynamic(() => import("./News")),
  news_card_list: dynamic(() => import("./NewsCardList")),
  our_history: dynamic(() => import("./OurHistory")),
  photos: dynamic(() => import("./Photos")),
  project_and_subprojects: dynamic(() => import("./ProjectAndSubprojects")),
  projects: dynamic(() => import("./Projects")),
  rich_text: dynamic(() => import("./RichText")),
  social_impact: dynamic(() => import("./SocialImpact")),
  social_media: dynamic(() => import("./SocialMedia")),
  stackholders: dynamic(() => import("./Stackholders")),
};
